FetchPushModified-v0:
  n_timesteps: 1000000
  policy: MultiInputPolicy
  learning_rate: 0.001
  batch_size: 2048
  buffer_size: 1000000
  gamma: 0.95
  tau: 0.05
  learning_starts: 1000
  policy_kwargs: dict(net_arch=[512, 512, 512], n_quantiles=25)
  replay_buffer_class: HerReplayBuffer
  replay_buffer_kwargs: dict(n_sampled_goal=4, goal_selection_strategy='future')
